# 서브쿼리에서 찾은 '종류'와 '최대 점수'가 모두 일치하는 행만 필터링
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
# 각 음식 종류별 최대 즐겨찾기를 따옴.
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;