-- 코드를 작성해주세요
SELECT 
    C.ITEM_ID, 
    C.ITEM_NAME, 
    C.RARITY
FROM 
    ITEM_INFO A, 
    ITEM_TREE B, 
    ITEM_INFO C
WHERE 
    A.ITEM_ID = B.PARENT_ITEM_ID
    AND B.ITEM_ID = C.ITEM_ID
    AND A.RARITY = 'RARE'
ORDER BY 
    C.ITEM_ID DESC;